/**
 * Included files
 */
#include "FileManager.h"
#include "src/entities/player/Player.h"
#include "src/entities/player/Inventory.h"
#include "src/items/Item.h"
#include "src/world/Zone.h"
#include <time.h>
#include <stdio.h>
#include <algorithm>

static const std::string SAVE_DATA_META_FILE = "data/save/.savefiles";

void FileManager::init() {
} // init

std::set<std::string> FileManager::getLoadablePlayers() {
    using namespace std;
    set<string> result;
    string playerName;
    ifstream savelist;

    savelist.open(SAVE_DATA_META_FILE);

    while (savelist.is_open() && !savelist.eof()) {
        getline(savelist, playerName);

        if (playerName.length() > 0) {
            result.insert(playerName);
        } // if
    } // while

    return result;
} // getLoadablePlayers

Player *FileManager::loadPlayer(std::string filepath) {
    Player *result = NULL;

    return result;
} // loadPlayer

void FileManager::updateSaveMetaFile(std::string playerName) {
    using namespace std;
    fstream file;
    set<string> savelist = getLoadablePlayers();

    savelist.insert(playerName);

    file.open(SAVE_DATA_META_FILE, fstream::out);

    for (string str : savelist) {
        file << str << endl;
    } // for

    file.close();
} // updateSaveMetaFile

void FileManager::savePlayer(int seed, Player *player, Zone *zone) {
    using namespace std;
    string filePath = "data/save/" + player->getName() + "_Save.sav";
    ofstream savefile;

    savefile.open(filePath);

    savefile << "# This save file was automatically generated by the game on" << endl;
    savefile << "# " << timestamp() << "." << endl;
    savefile << "# Editing this file may corrupt it if it is malformed." << endl;

    savefile << "name=" << player->getName() << endl;
    savefile << "level=" << player->getLevel() << endl;
    savefile << "hitpoints=" << player->getAttribute(hitpoints) << endl;
    savefile << "strength=" << player->getAttribute(strength) << endl;
    savefile << "armor=" << player->getAttribute(armor) << endl;
    savefile << "seed=" << seed << endl;
    savefile << "monsterLevel=" << zone->zoneLevel << endl;
    savefile << "monsterDifficulty=" << zone->monsterDifficulty << endl;
    savefile << "timePlayer=" << player->getTimePlayed() << endl;
    savefile << "isDead=" << (int)player->isDead() << endl;
    
    savefile << endl << "# Begin inventory list" << endl << endl;

    for (Item *item : player->getInventory()->getItems()) {
        savefile << item->getName() << "=" << item->getGoldWorth() << endl;
    } // for

    savefile << endl << "# End inventory list" << endl;

    savefile.close();

    updateSaveMetaFile(player->getName());
} // savePlayer

std::string FileManager::timestamp() {
    time_t     now = time(0);
    struct tm  tstruct;
    char       buf[80];
    tstruct = *localtime(&now);

    strftime(buf, sizeof(buf), "%Y-%m-%d.%X", &tstruct);

    return buf;
} // timestamp

std::fstream *FileManager::openFile(std::string filepath) {
    std::fstream *result = new std::fstream();

    result->open(filepath);

    if (!result->is_open()) {
        return NULL;
    } // if

    return result;
} // openFile

void FileManager::closeFile(std::fstream *file) {
    file->close();
} // closeFile

std::string FileManager::readLine(std::fstream *file) {
    std::string result;

    std::getline(*file, result);

    if (result.length() <= 1) {
        return "#";
    }

    return result;
} // readLine
